### PR TITLE
DragManager.java

### PR DESCRIPTION
**Pull request by RaoulFoaleng**

### CODE REVIEW

**Comment by vinc3m1** [comment]
No description? Why would viewholder be null ever?

**Comment by RaoulFoaleng** [comment]
Hi,

I am using DragSortAdapter in my app. I noticed that on some phones where the app is running recyclerView.findViewHolderForItemId(itemId) return null.

**Comment by RaoulFoaleng** [comment]
If you want to reproduce the test case I am talking about. 
You need to create a Fragment containing a ViewPager, and provide at least two RecyclerView item to the viewPager and make sure that the ID of each items present in each RecyclerView are unique.
You should get a NullPointerException.

**Comment by js-bonin** [comment]
Having this issue also, this fixed it for me as well... why won't you merge this?

**Pull request closed without merging**
